# column names - 17; after changed by Jichong (my bad)

new_feature_list_17 = ['AGE', 'WEATHER_GROUP_CLEAR/NORMAL','WEATHER_GROUP_FOG/CLOUDY','WEATHER_GROUP_RAIN/SLEET','WEATHER_GROUP_SNOW',
                        'LIGHT_Condition_DAWN/DUSK','LIGHT_Condition_LIGHT','ROAD_SURFACE_DRY','ROAD_SURFACE_WET','ROADWAY_GRADE_LEVEL',
                        'ROADWAY_ALIGNMENT_STRAIGHT','VEHICLE_TYPE_CAR','VEHICLE_TYPE_PICKUP','VEHICLE_TYPE_VAN','VEHICLE_YEAR_2008-2019',
                        'VEHICLE_YEAR_2011-2019','GENDER_FEMALE']

new_feature_list_9 = ['ROLL','WEATHER_GROUP','LIGHT_Condition','ROAD_SURFACE','ROADWAY_GRADE','ROADWAY_ALIGNMENT','VEHICLE_TYPE','VEHICLE_YEAR']

old_feature_list = ['WEATHER_GROUP','LIGHT_GROUP','SURFACE_GROUP','GRADE_GROUP','VEHICLE_TYPE','ALIGN_GROUP','MY_GROUP','GENDER_GROUP']